### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by wapmorgan**
The same as the previous one, but splitted into 2 commits.

### CODE REVIEW

**Comment by wapmorgan** [comment]
This commit without PSR-2 modifications.

**Comment by dimitri** [comment]
Thanks for the splitting, much easier to read now!

I see that the constants are all moved to a new file, which looks good. Also the manual *require* calls are removed. Is the lib still usable without composer? Should we care? What about compatibility for users of the current version?

**Comment by wapmorgan** [comment]
No, that's not usable without composer. But in 2K17 everybody knows composer and I think almost all projects use it.

**Comment by dimitri** [comment]
Hi, sorry for the delays: I tried to brush up my PHP skills and think about the compability break. Here's my thinking:

  - can we also introduce namespaces and follow PSR4 ?
  - should constants be declared as part of the classes ?

About compatibility,  I would tag the current branch as v1.0 and your work would then be part of version 2.0. We will have to edit at least the README about compatibility break and usage with composer.

Also if I understand correctly @gletournel might be interested into this work too, ping! (See https://github.com/dimitri/libphp-pgq/compare/master...gletournel:master)

What do you think?

**Comment by wapmorgan** [comment]
> can we also introduce namespaces and follow PSR4 ?
May be, but this will require more weeks to consider and implement.

> should constants be declared as part of the classes
I don't think so.

**Comment by wapmorgan** [comment]
So, what?

**Comment by dimitri** [comment]
Well I still think that that PR needs to implement namespaces and PSR4...

**Comment by wapmorgan** [comment]
Ok, I'll work on this soon.

**Comment by wapmorgan** [comment]
Introducting namespaces will break BC.

**Comment by wapmorgan** [comment]
Moved everything to `pgq` namespace.

**Comment by dimitri** [comment]
I see no reason to prevent merging! Do you want to do it yourself and be a maintainer of this PHP lib?

**Comment by wapmorgan** [comment]
I can merge it, but can't promise I could maintain this package.

**Comment by dimitri** [comment]
I just added you as a maintainer, so that you can tag/merge and fix bugs if some show up. Please feel free to merge!

**Comment by wapmorgan** [comment]
Ok, I've added it on packagist.org (https://packagist.org/packages/dimitri/libphp-pgq), but for auto-update information when new commits pushed, you need to set-up a Packagist hook in repo settings. For this you need to register on packagist.org and copy api token, which then paste in packagist hook settings.

**Comment by dimitri** [comment]
I'm now dimitri on packagist too, so if you add me there as a maintained I'll then add the API token and GitHub hook integration for this package. Thanks!

**Comment by wapmorgan** [comment]
Done. Now you can copy token from https://packagist.org/profile/ to create a packagist repo hook.

**Comment by dimitri** [comment]
Should be all good now, at least I managed to follow the steps!

**Pull request merged**
